modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
[[mods]]
modId = "awaken"
version = "${mod_version}"
displayName = "Awaken" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforge.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/MinecraftFom/AwakenMod-NeoForge"
authors = "Owner: FomsDev(fomdev)\nProgram: Fom477\nDesign: Fom477, modic_M, Sixawns, SukISU117\nArt: modic_M, Sixawns"

description = '''Wake before you Awake!'''

[[mixins]]
config = "awaken.mixins.json"
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.awaken]]
modId = "neoforge"
type = "required"
reason = "Mod Loader *LOL*"
versionRange = "[21, )"
ordering = "NONE"
side = "BOTH"
[[dependencies.awaken]]
modId = "minecraft"
type = "required"
reason = "Game Itself *LOL*"
versionRange = "[1.21.1, 1.22)"
ordering = "NONE"
side = "BOTH"
